---
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "https://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "abcdefghijklmnopqrstuvwxyz1234567890"


xpack.security.encryptionKey: "something_at_least_32_characters"
xpack.security.session.idleTimeout: "1h"
xpack.security.session.lifespan: "30d"
#
elasticsearch.username: elastic
elasticsearch.password: changeme
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/newfile.crt.pem
server.ssl.key: /usr/share/kibana/newfile.key.pem
elasticsearch.ssl.verificationMode: none

